# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# Invenio Services is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  redis:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    restart: "always"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DB}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
  psql:
    image: postgres:${PSQL_VERSION}
    restart: "always"
    environment:
      - "POSTGRES_USER=${PSQL_USER}"
      - "POSTGRES_PASSWORD=${PSQL_PASSWORD}"
      - "POSTGRES_DB=${PSQL_DB}"
    ports:
      - "5432:5432"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9300:9300"
