# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 CERN.
# Copyright (C) 2025 KTH Royal Institute of Technology.
#

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    uses: inveniosoftware/workflows/.github/workflows/pypi-publish.yml@master
    secrets: inherit
    with:
      babel-compile-catalog: true
